[project]
name = 'Decentralized-Energy-Trading-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.energy-production-tracking]
path = 'contracts/energy-production-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.grid-management]
path = 'contracts/grid-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.peer-to-peer-trading]
path = 'contracts/peer-to-peer-trading.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
